server:
  port: 9094
spring:
  application:
    name: userservice
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/rides
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

